NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

net_tomas_kadlec_lunch_guy_api_base:
    path:     /api/v1

net_tomas_kadlec_lunch_guy_api:
    resource: "@NetTomasKadlecLunchGuyApiBundle/Controller/DefaultController.php"
    type:     rest
    prefix:   /api/v1/

net_tomas_kadlec_lunch_guy_ui:
    resource: "@NetTomasKadlecLunchGuyUiBundle/Controller/"
    type:     annotation
    prefix:   /
