apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: APP_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: APP_NAME
        role: APP_ROLE
        tier: APP_TIER
    spec:
      containers:
      - name: APP_NAME
        image: IMAGE_URL
        env: 
        - name: TZ
          value: "Europe/Prague"
        resources:
          requests:
            memory: "128Mi"
            cpu: "40m"
          limits:
            memory: "256Mi"
            cpu: "65m"
        ports:
        - name: frontend
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 180
          timeoutSeconds: 5
#        readinessProbe:
#          httpGet:
#            path: /
#            port: 80
#          initialDelaySeconds: 5
#          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: APP_NAME
  labels:
    app: APP_NAME
    role: APP_ROLE
    tier: APP_TIER
spec:
  selector:
    app: APP_NAME
    role: APP_ROLE
    tier: APP_TIER
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
  selector:
    app: APP_NAME
